Base:
    log_root: /content/drive/MyDrive/logs/
    model_root: './checkpoints/'
    num_workers: 4
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

SimCEN:
    model: SimCEN
    dataset_id: Criteo_x4_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    hidden_units: [480, 480, 480]
    ego_hidden_activations: relu
    v1_hidden_activations: leaky_relu
    v2_hidden_activations: relu
    ego_batch_norm: False
    v1_batch_norm: False
    v2_batch_norm: False
    through_dropout: 0.1
    ego_dropout: 0
    v1_dropout: 0
    v2_dropout: 0
    alpha: 0.01
    cl_temperature: 2.0
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

HRM:
    model: HRM
    dataset_id: KKBox_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    batch_norm: True
    layers:
      - high:
          hidden_units: [ 512 ]
          hidden_activations: relu
        low:
          hidden_units: [ 2048, 1024, 512 ]
          hidden_activations: relu
      - high:
          hidden_units: [ 256 ]
          hidden_activations: relu
        low:
          hidden_units: [ 1024, 512, 256 ]
          hidden_activations: relu
      - high:
          hidden_units: [ 128 ]
          hidden_activations: relu
        low:
          hidden_units: [ 512, 256, 128 ]
          hidden_activations: relu
    fc:
      hidden_units: [64, 32, 1]
      hidden_activations: relu
      batch_norm: False
      output_dim: 1
    ego_hidden_activations: relu
    v1_hidden_activations: leaky_relu
    v2_hidden_activations: relu
    ego_batch_norm: False
    v1_batch_norm: False
    v2_batch_norm: False
    through_dropout: 0.1
    ego_dropout: 0
    v1_dropout: 0
    v2_dropout: 0
    alpha: 0.01
    cl_temperature: 2.0
    dropout_rate: 0.1
    epochs: 20
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

AutoInt_test:
    model: AutoInt
    dataset_id: KKBox_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    net_dropout: 0
    num_heads: 2
    attention_layers: 3
    attention_dim: 8
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DCNv2_test:
    model: DCNv2
    dataset_id: KKBox_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    stacked_dnn_hidden_units: [64, 32]
    parallel_dnn_hidden_units: [64, 32]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'